---
output: 
  revealjs::revealjs_presentation:
    theme: white
    transition: none
    css: custom.css
    self_contained: false
    center: true
    reveal_plugins: ["notes"]
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, error=FALSE, dpi = 400,fig.cap = "", cache = T, echo=TRUE)
library(tidyverse)
library(glue)
```

# Erilliskysymyksiä

##

- Tierien kopiointi 
- Paikannimet
- Tulostusnäkymät

- Lisäkysymykset tervetulleita!

# Tierien kopiointi

## Kopiointimenetelmät

- Tier > Create Annotations from Dependent Tiers
- Tier > Copy Annotations from Tier to Tier
    - Tätä voisi käyttää myös hakutulosten järjestämiseen
    - … eli käyttää filtteröivää kopiointia ns. hakuna

## {data-background-image="https://imgur.com/rWnR69Y.png" data-background-size="70%"}

##

- Tier > Merge tiers
- File > Merge transcriptions

- Osa luo uuden tiedoston!

# Paikannimet

- Mikä on paikannimien rooli Elan-tiedostoissa?
    - Nauhoitetut esimerkit
    - Primääritallenne, jossa on myös muu tieto
    - Missä muodossa paikannimiaineistoa säilytetään?

- Vertautuu ehkä hieman skannattuihin dokumentteihin
    - Ei täysin sovi Elaniin paikannimien tutkimuksen puolesta
    - … mutta Elanissa voi silti säilyttää paikannimien nauhoituksia ja esiintymien annotointeja!

## {data-background-image="https://www.kotus.fi/files/5955/lippu_HOLLOLA_Keijumaki.jpg" data-background-size="50%"}

Lähde: [Kotus](https://www.kotus.fi/aineistot/nimiaineistot/paikannimikokoelmat)

##

- Mikä on paikannimikortin digitaalinen jälkeläinen?

## Paikannimet ja kieliteknologia

- Analyysin kannalta tiedosto voi olla lähes missä tahansa muodossa
- Excel ei ehkä paras, mutta CSV sopii
    - Editointi Excelissä tai LibreOfficessa, tallennus CSV-muodossa
    - Ei salli värikoodausta yms., mutta tiedosto on paremmin turvassa

# Tulostusnäkymät

## Useita vaihtoehtoja

- Halutaanko PDF vai HTML?